[general]

[default_bridge]
type=bridge
video_mode=none
sound_only_person=
sound_only_one=
sound_has_joined=
sound_has_left=
sound_kicked=
sound_muted=
sound_unmuted=
sound_binaural_on=
sound_binaural_off=
sound_locked=
sound_unlocked=
sound_error_menu=
sound_begin=

[default_user]
type=user
admin=no
marked=no
startmuted=no
music_on_hold_when_empty=no
quiet=yes
announce_user_count=no
announce_join_leave=no
dtmf_passthrough=no
hold_announce=no
