[general]

[featuremap]
blindxfer => *3         ; Press *3 during call to blind transfer
atxfer => *2            ; Press *2 during call for attended transfer
parkcall => *5          ; Press *5 during call to park it

[applicationmap]
