[modules]
autoload=yes

load => res_pjsip.so
load => res_pjsip_session.so
load => chan_pjsip.so
load => app_confbridge.so
load => bridge_softmix.so
load => app_voicemail.so
load => app_queue.so
load => app_dial.so
load => app_playback.so
load => app_echo.so
load => res_musiconhold.so
load => format_wav.so
load => format_pcm.so
