[general]
persistentmembers = yes
monitor-type = MixMonitor

[support_queue]
strategy = ringall
timeout = 15
retry = 5
maxlen = 0
announce-frequency = 30
announce-holdtime = yes
announce-position = yes
musicclass = default
member => PJSIP/1001
member => PJSIP/1002

[sales_queue]
strategy = rrmemory
timeout = 20
retry = 5
maxlen = 10
announce-frequency = 45
announce-holdtime = yes
musicclass = default
member => PJSIP/1003
