[general]

[default]
parkext => 770                    ; Park calls by dialing 700
parkpos => 701-710                ; Parking slots 701-710
context => parkedcalls            ; Context for parked calls
parkingtime => 45                 ; Timeout after 45 seconds
comebacktoorigin => yes           ; Return to parker if not picked up
courtesytone = beep               ; Play beep when call is retrieved
parkedplay = caller               ; Who hears the parking slot number
